pipeline {
    agent any
    parameters {
		string(name: 'BASTION_SERVER_IP', defaultValue: '', description: 'Bastion server IP to deploy')
    }

	environment {
		BASTION_SERVER_IP = ""
		path = "cicd/demo"
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'cd configure-pods/'            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
        stage('Print Message') {
            steps {
                script {
                    def BASTION_SERVER_IP = params.BASTION_SERVER_IP
                    echo BASTION_SERVER_IP
                }
            }
		steps {
			dir {env.path}
                 	script {
                    		cat abc.txt
                	}
            }
        }
    }
}
