pipeline {
    agent any
    parameters {
		string(name: 'BASTION_SERVER_IP', defaultValue: '', description: 'Bastion server IP to deploy')
    }

	environment {
		BASTION_SERVER_IP = ""
		PATH_F = "k8s/configure-pods"
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                sh 'cd configure-pods/'            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
		sh 'ls -lrth'
		sh 'pwd'
            }
        }
        stage('Print Message') {
            steps {
                script {
			dir(PATH_F){
			    sh "cat pod.yml || true"
			    sh "ls -ls"
			    sh "pwd" 
	                    def BASTION_SERVER_IP = params.BASTION_SERVER_IP
	                    echo BASTION_SERVER_IP
                	}
		}
	    }
	}
    }
}
